networks:
  network3:
    name: network3

services:
  nginx:
    container_name: nginx3
    build: ./nginx
    ports:
     - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - network3
    depends_on:
      - php
      - mysql
  
  php:
    container_name: php3
    build: ./php-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - network3
    depends_on:
      - mysql
  
  mysql:
    container_name: mysql3
    build: ./mysqlDocker
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network3
